version: '3.8'
services:
  app:
    image: crm:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/crm
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      AWS_S3_ACCESS_KEY: AKIAWAA66JWEDWCPSYXQ
      AWS_S3_REGION: eu-north-1
      AWS_S3_BUCKET_NAME: crm-qa-images
      AWS_S3_SECRET_KEY: CIppKB3VDNelwXv1vCtI1HpNlhcHP+mPPAumKUlU
      SECURITY_JWT_SECRET_KEY: 1c19b1448421bb43f392ff07eea2758c8170b42b3b852347604058a1b32f1e80
      SECURITY_JWT_EXPIRATION_TIME: 3600000
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crm
    ports:
      - "5432:5432"
